LanchoneteAspMvc/Areas/Admin/Controllers/AdminPedidosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LanchoneteAspMvc.Data.Context;
using LanchoneteAspMvc.Models;
using LanchoneteAspMvc.Data.Interfaces;
using LanchoneteAspMvc.Areas.Admin.Repositories;
using ReflectionIT.Mvc.Paging;
using LanchoneteAspMvc.ViewModels;

namespace LanchoneteAspMvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminPedidosController : Controller
    {
        private readonly IPedidoRepository _pedidoRepository;

        public AdminPedidosController(IPedidoRepository pedidoRepository)
        {
            _pedidoRepository = pedidoRepository;
        }


        //public async Task<IActionResult> Index()
        //{
        //    var pedidos = await _pedidoRepository.GetAll();
        //    return View(pedidos);
        //}

        public IActionResult PedidoLanche(Guid id)
        {
             var pedidoLanche = _pedidoRepository.RetornaContext()
                    .Pedidos
                    .Include(p => p.PedidoDetalhes)
                    .ThenInclude(p => p.Lanche)
                    .ThenInclude(p => p.Categoria)
                    .FirstOrDefault(p => p.Id == id);
            if (pedidoLanche == null)
            {
                Response.StatusCode = 404;
                return View("PedidoNotFound", id);
            }
            PedidoLancheVM pedidoLancheVM = new PedidoLancheVM()
            {
                Pedido = pedidoLanche,
                PedidoDetalhes = pedidoLanche.PedidoDetalhes
            };

            return View(pedidoLancheVM);

        }
               

        public async Task<IActionResult> Index(string filter, int pageindex = 1, string sort = "Nome")
        {

            var resultado = _pedidoRepository.RetornaContext().Pedidos.AsNoTracking().AsQueryable();
            if(!string.IsNullOrWhiteSpace(filter))
            {
                resultado = resultado.Where(p => p.Nome.Contains(filter));
            }

            var model = await PagingList.CreateAsync(resultado, 5, pageindex, sort, "Nome");
            model.RouteValue = new RouteValueDictionary { { "filter", filter } };
            return View(model);
        }

        public async Task<IActionResult> Details(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedido = await _pedidoRepository.Get(id);

            if (pedido == null)
            {
                return NotFound();
            }

            return View(pedido);
        }

        // GET: Admin/AdminPedidos/Create
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Pedido pedido)
        {
            if (ModelState.IsValid)
            {

                _pedidoRepository.CriarPedido(pedido);
                return RedirectToAction(nameof(Index));
            }
            return View(pedido);
        }

        // GET: Admin/AdminPedidos/Edit/5
        public async Task<IActionResult> Edit(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedido = await _pedidoRepository.Get(id);
            if (pedido == null)
            {
                return NotFound();
            }
            return View(pedido);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Nome,Sobrenome,Endereco,Estado,Cidade,Telefone,Email,PedidoTotal,TotalItensPedido,PedidoEnviado,PedidoEntregueEm,Id")] Pedido pedido)
        {
            if (id != pedido.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _pedidoRepository.Put(pedido);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (await PedidoExists(pedido.Id))
                    {
                        throw;
                    }
                    else
                    {
                        return NotFound();
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pedido);
        }

        // GET: Admin/AdminPedidos/Delete/5
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedido = await _pedidoRepository.Get(id);
            if (pedido == null)
            {
                return NotFound();
            }

            return View(pedido);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var pedido = await _pedidoRepository.Get(id);

            if (pedido != null)
            {
                await _pedidoRepository.Delete(id);
            }

            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> PedidoExists(Guid id)
        {
            var pedido = await _pedidoRepository.Get(id);
            return pedido == null ? true : false;
        }
    
        
    }
}

LanchoneteAspMvc/Areas/Admin/Views/AdminPedidos/Create.cshtml
@model LanchoneteAspMvc.Models.Pedido

@{
    ViewData["Title"] = "Create";
}

<section class="container">


<h4>Pedido</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sobrenome" class="control-label"></label>
                <input asp-for="Sobrenome" class="form-control" />
                <span asp-validation-for="Sobrenome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Endereco" class="control-label"></label>
                <input asp-for="Endereco" class="form-control" />
                <span asp-validation-for="Endereco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cidade" class="control-label"></label>
                <input asp-for="Cidade" class="form-control" />
                <span asp-validation-for="Cidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefone" class="control-label"></label>
                <input asp-for="Telefone" class="form-control" />
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PedidoTotal" class="control-label"></label>
                <input asp-for="PedidoTotal" class="form-control" />
                <span asp-validation-for="PedidoTotal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalItensPedido" class="control-label"></label>
                <input asp-for="TotalItensPedido" class="form-control" />
                <span asp-validation-for="TotalItensPedido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PedidoEntregueEm" class="control-label"></label>
                <input asp-for="PedidoEntregueEm" class="form-control" />
                <span asp-validation-for="PedidoEntregueEm" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-outline-primary"><i class="fa-solid fa-reply"></i></a>
            </div>
        </form>
    </div>
</div>

</section>

LanchoneteAspMvc/Areas/Admin/Views/AdminPedidos/Delete.cshtml
@model LanchoneteAspMvc.Models.Pedido

@{
    ViewData["Title"] = "Delete";
}

<section class="container">


<h3>Você irá excluir @Model.Nome</h3>
<div>
    <h4>Pedido</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sobrenome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sobrenome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Endereco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Endereco)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cidade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cidade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PedidoTotal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PedidoTotal)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalItensPedido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalItensPedido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PedidoEnviado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PedidoEnviado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PedidoEntregueEm)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PedidoEntregueEm)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> 
        <a asp-action="Index" class="btn btn-outline-primary"><i class="fa-solid fa-reply"></i></a>
    </form>
</div>
</section>

LanchoneteAspMvc/Areas/Admin/Views/AdminPedidos/Details.cshtml
@model LanchoneteAspMvc.Models.Pedido

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Pedido</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sobrenome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sobrenome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Endereco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Endereco)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cidade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cidade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PedidoTotal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PedidoTotal)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalItensPedido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalItensPedido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PedidoEnviado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PedidoEnviado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PedidoEntregueEm)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PedidoEntregueEm)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-success">Editar</a>
    <a asp-action="Index" class="btn btn-outline-primary"><i class="fa-solid fa-reply"></i></a>
</div>

LanchoneteAspMvc/Areas/Admin/Views/AdminPedidos/Edit.cshtml
@model LanchoneteAspMvc.Models.Pedido

@{
    ViewData["Title"] = "Admin";
    var codigoPedido = Model.Id.ToString().Replace(".", " ").Substring(0, 8);
}

<h4>Código Pedido: @codigoPedido</h4>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sobrenome" class="control-label"></label>
                <input asp-for="Sobrenome" class="form-control" />
                <span asp-validation-for="Sobrenome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Endereco" class="control-label"></label>
                <input asp-for="Endereco" class="form-control" />
                <span asp-validation-for="Endereco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cidade" class="control-label"></label>
                <input asp-for="Cidade" class="form-control" />
                <span asp-validation-for="Cidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefone" class="control-label"></label>
                <input asp-for="Telefone" class="form-control" />
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PedidoTotal" class="control-label"></label>
                <input asp-for="PedidoTotal" class="form-control" />
                <span asp-validation-for="PedidoTotal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalItensPedido" class="control-label"></label>
                <input asp-for="TotalItensPedido" class="form-control" />
                <span asp-validation-for="TotalItensPedido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PedidoEnviado" class="control-label"></label>
                <input asp-for="PedidoEnviado" class="form-control" />
                <span asp-validation-for="PedidoEnviado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PedidoEntregueEm" class="control-label"></label>
                <input asp-for="PedidoEntregueEm" class="form-control" />
                <span asp-validation-for="PedidoEntregueEm" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group mt-4">
                <input type="submit" value="Editar" class="btn btn-success" />
                <a asp-action="Index" class="btn btn-outline-primary"><i class="fa-solid fa-reply"></i></a>
            </div>
        </form>
    </div>
</div>

LanchoneteAspMvc/Areas/Admin/Views/AdminPedidos/Index.cshtml
@model ReflectionIT.Mvc.Paging.IPagingList<Pedido>

@{
    Func<string, string> mask = (tel) => long.Parse(tel).ToString("(##) #####-####"); 
}
<section class="container">

<form method="get" class="form-control mt-3">
    <div class="mb-3">       
        <input name="filter" class="form-control" placeholder="filtro" value="@Model.RouteValue["filter"]"/>
        <button type="submit" class="btn btn-info mt-2">
            <i class="fa fa-search"></i>
        </button>
    </div>

</form>


<p class="mt-3">
    <a asp-action="Create" class="btn btn-success"><i class="fa-solid fa-file-circle-plus"></i> - Novo</a>
</p>

    <table class="table">
        <thead >
            <tr class="text-center">
                <th scope="col">Nome comleto</th>
                <th scope="col">Endereço</th>
                <th scope="col">Cidade</th>
                <th scope="col">Estado</th>
                <th scope="col">Telefone</th>
                <th scope="col">E-mail</th>
                <th scope="col">Total</th>
                <th scope="col">itens do Pedido</th>
                <th scope="col">Data do Envio</th>
                <th scope="col">Data da Entrega</th>
                <th scope="col">Ação</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr class="text-center align-baseline">
                    <th scope="row">@item.Nome @item.Sobrenome </th>
                    <td>@Html.DisplayFor(modelItem => item.Endereco)</td>
                    <td>@Html.DisplayFor(modelItem => item.Cidade)</td>
                    <td>@Html.DisplayFor(modelItem => item.Estado)</td>
                    <td>@mask(item.Telefone)</td>
                    <td>@Html.DisplayFor(modelItem => item.Email)</td>
                    <td>@item.PedidoTotal.ToString("C")</td>
                    <td>
                        <a asp-action="PedidoLanche" asp-route-id="@item.Id" 
                            name="id" class="btn btn-primary">
                            @item.TotalItensPedido
                        </a>
                    </td>
                    <td>@Html.DisplayFor(modelItem => item.PedidoEnviado)</td>
                    <td>@Html.DisplayFor(modelItem => item.PedidoEntregueEm)</td>
                    <td class="d-flex justify-content-center align-items-center">
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary "><i class="fa fa-edit"></i></a>
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-warning me-2 ms-2"><i class="fa fa-circle-info"></i></a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger "><i class="fa fa-trash"></i></a>
                    </td>
            </tr>
            }
        </tbody>
    </table>

<p>Total de pedidos: @Model.TotalRecordCount</p>
<div>
    <vc:pager paging-list="@Model"></vc:pager>
</div>
</section>

LanchoneteAspMvc/Areas/Admin/Views/AdminPedidos/PedidoLanche.cshtml
@model LanchoneteAspMvc.ViewModels.PedidoLancheVM

@{
    var pedido = Model.Pedido;
    var lanche = Model.PedidoDetalhes;
}
<section class="container">
    <section class="row mt-4">
        <div class="col-6">
            <h3 >Dados do Pedido</h3>
        </div> 
        <div class="col-6 text-end">
            <a asp-action="Index" class="btn btn-outline-primary"><i class="fa-solid fa-reply"></i></a>
        </div>
 
    </section>
    <hr />
    <h4>Código: @pedido.Id.ToString().Replace(".", " ").Substring(0,8).ToUpper()</h4>
    <br />
    <p class="h5 ">Cliente: @pedido.Nome</p>
    <p class="h5 ">Data: @pedido.PedidoEnviado</p>
    <p class="h5 ">Entrega: @pedido.PedidoEntregueEm</p>
    <hr />

        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Categoria</th>
                    <th>Lanche</th>
                    <th>Preço</th>
                    <th>Subtotal</th>
                </tr>
            </thead>
            <tbody>
            @foreach(var item in lanche)
            {
                <tr>
                    <td>@item.Lanche.Categoria.Nome</td>
                    <td><img src="@item.Lanche.ImagemUrl" width="50px" /></td>
                    <td>@item.Lanche.Preco.ToString("C") (@item.Quantidade)</td>
                    @{
                        var subtotal = item.Lanche.Preco * item.Quantidade;
                    }
                    <td>@subtotal.ToString("C")</td>

                </tr>
            }
            </tbody>
        </table>

    <div class="row">
        <div class="col-12 text-end">
            <span class="h5">Total do Pedido: @pedido.PedidoTotal.ToString("C") </span>
        </div>
    </div>

</section>

LanchoneteAspMvc/Areas/Admin/Views/AdminPedidos/PedidoNotFound.cshtml
<section class="container">
    <h1>PEDIDO NÃO ENCONTRADO</h1>
</section>
<a asp-action="Index" asp-controller="AdminPedidos" class="btn btn-link">
    <span>Retorna para lista</span>
</a>