LanchoneteAspMvc/Areas/Admin/Controllers/AdminGraficoController.cs
using LanchoneteAspMvc.Areas.Admin.Services;
using Microsoft.AspNetCore.Mvc;

namespace LanchoneteAspMvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminGraficoController : Controller
    {
        private readonly GraficoVendasService _graficoVendas;

        public AdminGraficoController(GraficoVendasService graficoVendasService)
        {
            _graficoVendas = graficoVendasService;
        }

        [HttpGet]
        public IActionResult Index(int dias)
        {
            return View();
        } 
        
        [HttpGet]
        public IActionResult VendasSemanal(int dias)
        {
            return View();
        }

        [HttpGet]
        public IActionResult VendasMensal(int dias)
        {
            return View();
        }

        public JsonResult VendasLanches(int dias)
        {
            var lanchesVendas = _graficoVendas.ObterVendaLanches(dias);

            return Json(lanchesVendas);
        }
    }
}

LanchoneteAspMvc/Areas/Admin/Views/AdminGrafico/Index.cshtml
@{
    ViewData["Title"] = "Gráfico de Vendas";
}

<title >
    @ViewData["Title"]
</title>

<h2>Gráfico de vendas Anual</h2>
<hr />
<section class="container" >
    <div id="grafico"></div>
</section>

 
<script>
    google.charts.load('current', { packages: ['corechart'] });
    google.charts.setOnLoadCallback(carregaDados);
    async function carregaDados() {

        const url = '@Url.Action("VendasLanches", "AdminGrafico", new { dias = 360})';
 
        const requisicao = await fetch(url)
        const dados = await requisicao.json();
        console.log(dados)
        let informacoesGrafico = [
            ["Nome", "Quantidade", "Valores(R$)", { role: 'style' }]
        ]
        $.each(dados, (i, item) => {
            informacoesGrafico.push([item.nome, item.quantidade, item.valorTotal, `color: #${i}8F5FF`]);
        });

        geraGrafico(informacoesGrafico);

    }

    function geraGrafico(dados) {

        let view = google.visualization.arrayToDataTable(dados);

        const options = {
            width: '1000',
            height: '400',
            bar: { groupWidth: '75%' },
            isStacked: true,
            'legend': 'left',
            'is3D': true,

        }
        
        const grafico = new google.visualization.BarChart(document.getElementById("grafico"));

        grafico.draw(view, options)

    }
</script>

LanchoneteAspMvc/Areas/Admin/Views/AdminGrafico/VendasMensal.cshtml
@{
    ViewData["Title"] = "Gráfico de Vendas";
}

<title>
    @ViewData["Title"]
</title>

<h2>Gráfico de vendas Mensal</h2>
<hr />
<section class="container">
    <div id="grafico"></div>
</section>

<script>
    google.charts.load('current', { packages: ['corechart'] });
    google.charts.setOnLoadCallback(carregaDados);

    async function carregaDados() {

        const url = '@Url.Action("VendasLanches", "AdminGrafico", new { dias = 30 })';

        const requisicao = await fetch(url)
        const dados = await requisicao.json();
   
        let informacoesGrafico = [
            ["Nome", "Quantidade", "Valores(R$)", { role: 'style' }]
        ]
        $.each(dados, (i, item) => {
            informacoesGrafico.push([item.nome, item.quantidade, item.valorTotal, `color: #FFA${i}00`]);
        });

        geraGrafico(informacoesGrafico);

    }

    function geraGrafico(dados) {

        if(!dados){
            $("#graficos").html("<h2>Não há Dados</h2>")
        }

        let view = google.visualization.arrayToDataTable(dados);
       
       
        const options = {
            width: '100%',
            height: '500',
            bar: { groupWidth: '75%' },
            isStacked: true,
            'legend': 'left',
            'is3D': true,
            
        }
        
        const grafico = new google.visualization.ColumnChart(document.getElementById("grafico"));

        grafico.draw(view, options)

    }
</script>

LanchoneteAspMvc/Areas/Admin/Views/AdminGrafico/VendasSemanal.cshtml
@{
    ViewData["Title"] = "Gráfico de Vendas";
}

<title>
    @ViewData["Title"]
</title>

<h2>Gráfico de vendas Semanal</h2>
<hr />
<section class="container">
    <div id="grafico"></div>
</section>

<script>
    google.charts.load('current', { packages: ['corechart'] });
    google.charts.setOnLoadCallback(carregaDados);

    async function carregaDados() {

        const url = '@Url.Action("VendasLanches", "AdminGrafico", new { dias = 7 })';

        const requisicao = await fetch(url)
        const dados = await requisicao.json();
       
        let informacoesGrafico = [
            ["Nome", "Quantidade", "Valores(R$)", { role: 'style' }]
        ]
        $.each(dados, (i, item) => {
            informacoesGrafico.push([item.nome, item.quantidade, item.valorTotal, `color: #FFA${i}00`]);
        });

        
        const tag = document.getElementById("grafico")
        if (dados.length < 1) {
            tag.innerHTML = "<h2>Não há dados de venda nesse período.</h2>"
        } else {
            geraGrafico(informacoesGrafico);
        }
    }

    function geraGrafico(dados) {       

            const tag = document.getElementById("grafico")
            let view = google.visualization.arrayToDataTable(dados);

        const options = {
            width: '1000',
            height: '400',
            bar: { groupWidth: '75%' },
            isStacked: true,
            'legend': 'left',
            'is3D': true,

        }

            const grafico = new google.visualization.BarChart(tag);
            grafico.draw(view, options)       
    }

</script>