LanchoneteAspMvc/Models/Lanche.cs
namespace LanchoneteAspMvc.Models
{
    public class Lanche : Entidade
    {
        public string Nome { get; set; }
        public decimal Preco { get; set; }
        public string DescricaoCurta { get; set; }
        public string DescricaoLonga { get; set; }
        public string ImagemUrl { get; set; }
        public string ThumbnailUrl { get; set; }
        public bool Preferido { get; set; }
        public bool Disponivel { get; set; }

        /*EF Core*/
        public Guid CategoriaId { get; set; }
        public Categoria? Categoria { get; set; }

    }
}

LanchoneteAspMvc/ViewModels/CatalogoViewModel.cs
using LanchoneteAspMvc.Models;

namespace LanchoneteAspMvc.ViewModels;

public class CatalogoViewModel
{
    public List<Lanche> Lanches { get; set; }
    public string CategoriaAtual { get; set; }
}

LanchoneteAspMvc/Controllers/LancheController.cs
using LanchoneteAspMvc.Data.Interfaces;
using LanchoneteAspMvc.Models;
using LanchoneteAspMvc.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;

namespace LanchoneteAspMvc.Controllers
{
    [Authorize]
    public class LancheController : Controller
    {
        private readonly ILancheRepository _lancheRepository;

        public LancheController(ILancheRepository lancheRepository)
        {
            _lancheRepository = lancheRepository;
        }

        [AllowAnonymous]
        public async Task<ActionResult> Catalogo(string categoria)
        {
            
            List<Lanche> lanches;
            string categoriaAtual = "";

            if(string.IsNullOrEmpty(categoria))
            {
                lanches = await _lancheRepository.GetAll();
                categoriaAtual = "Todos os Lanches";
            }
            else
            {
                lanches = await _lancheRepository.LanchesPorCategoria(categoria) ;
                categoriaAtual = categoria;
            }

            var catalogo = new CatalogoViewModel()
            {
                Lanches = lanches,
                CategoriaAtual = categoriaAtual
            
            };

            return View(catalogo);
        }

        public async Task<IActionResult> Detalhes(Guid id)
        {
            var lanche = await _lancheRepository.Get(id);

            return View(lanche);
        }

        public async Task<ViewResult> Buscar(string busca)
        {
            List<Lanche> lanches;
            string categoriaAtual = string.Empty;

            if(string.IsNullOrEmpty(busca))
            {
                lanches = await _lancheRepository.GetAll();
            }
            else
            {
                lanches = await _lancheRepository.Buscar(l => l.Nome.ToLower().Contains(busca.ToLower())) ;
                if(lanches.Any()) 
                {
                    categoriaAtual = "Lanches";
                }
                else
                {
                    categoriaAtual = string.Empty;
                }
            }
            var catalogo = new CatalogoViewModel()
            {
                Lanches = lanches,
                CategoriaAtual = categoriaAtual
            };

            return View("~/Views/Lanche/Catalogo.cshtml", catalogo);

        }
    }
}

LanchoneteAspMvc/Views/Lanche/Catalogo.cshtml
@model CatalogoViewModel;

@{
    ViewData["Title"] = @Model.CategoriaAtual;
}


<section class="section-catalogo container-fluid ">

    <h1>CATÁLOGO DE LANCHES - @Model.CategoriaAtual </h1>
    <div class="mt-5 mb-5">
        <partial name="_FormBuscaLanches" />
    </div>
    <hr />
    <div class="catalogo">

            @if (Model.Lanches.Count < 1)
            {
                @if (@Model.CategoriaAtual.Any())
                {
                    <h3>Ainda Não há Lanches para Categoria @Model.CategoriaAtual :(</h3>
                }
                else
                {                
                    <h3>Nenhum lanche encontrado :(</h3>
                }
            }
            else
            {            
                @foreach(var item in Model.Lanches)
                {
                
                   <partial name="_DetalhesLanche" for="@item" />    
              
                }
            }

    </div>
</section>

LanchoneteAspMvc/Views/Lanche/Detalhes.cshtml
<div class="card" style="width: 18rem;">
    <img class="card-img-top" src="@Model.ThumbnailUrl" alt="Imagem de capa do card">
    <div class="card-body">
        <h5 class="card-title">@Model.Nome</h5>
        <h3 class="text-primary">@Model.Preco.ToString("C")</h3>
        <p class="card-text">@Model.DescricaoLonga.</p>
        <a asp-controller="Lanche"
           asp-action="Catalogo"
           class="btn btn-info">
            Voltar
       </a>
        <a asp-controller ="Carrinho"
           asp-action="AdicionarItem"
           asp-route-lancheId="@Model.Id" 
           class="btn btn-primary">
           Adicionar
       </a>
    </div>
</div>